# Generated by Django 3.1.5 on 2021-02-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('instagram', models.CharField(max_length=30)),
                ('facebook', models.CharField(max_length=30)),
                ('imo', models.CharField(max_length=30)),
                ('twitter', models.CharField(max_length=30)),
                ('aboutus', models.CharField(max_length=30)),
                ('references', models.CharField(max_length=30)),
                ('fax', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('smtpserver', models.CharField(max_length=30)),
                ('smtpemail', models.CharField(max_length=30)),
                ('smtppassword', models.CharField(max_length=30)),
                ('smtpport', models.CharField(max_length=30)),
                ('keywords', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('status', models.CharField(choices=[('True', 'Hawa'), ('False', 'Yok')], max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
