# Generated by Django 3.1.5 on 2021-02-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='image',
            new_name='icon',
        ),
        migrations.AlterField(
            model_name='settings',
            name='aboutus',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='address',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='settings',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='facebook',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='settings',
            name='fax',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='settings',
            name='imo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='settings',
            name='instagram',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='settings',
            name='keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='settings',
            name='references',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='settings',
            name='smtpemail',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='settings',
            name='smtppassword',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='settings',
            name='smtpport',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='settings',
            name='twitter',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
