# Generated by Django 3.1.5 on 2021-02-06 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210206_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='icon',
            new_name='image',
        ),
    ]
